/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkoutsImport } from './routes/workouts'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as ExercisesImport } from './routes/exercises'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WorkoutsRoute = WorkoutsImport.update({
  path: '/workouts',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ExercisesRoute = ExercisesImport.update({
  path: '/exercises',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exercises' | '/login' | '/signup' | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exercises' | '/login' | '/signup' | '/workouts'
  id: '__root__' | '/' | '/exercises' | '/login' | '/signup' | '/workouts'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesRoute: typeof ExercisesRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WorkoutsRoute: typeof WorkoutsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesRoute: ExercisesRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WorkoutsRoute: WorkoutsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/exercises",
        "/login",
        "/signup",
        "/workouts"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/exercises": {
      "filePath": "exercises.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/workouts": {
      "filePath": "workouts.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
