/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkoutsImport } from './routes/workouts'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as ExercisesImport } from './routes/exercises'
import { Route as CreateExerciseImport } from './routes/create-exercise'
import { Route as IndexImport } from './routes/index'
import { Route as WorkoutsCreateImport } from './routes/workouts.create'

// Create/Update Routes

const WorkoutsRoute = WorkoutsImport.update({
  path: '/workouts',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ExercisesRoute = ExercisesImport.update({
  path: '/exercises',
  getParentRoute: () => rootRoute,
} as any)

const CreateExerciseRoute = CreateExerciseImport.update({
  path: '/create-exercise',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkoutsCreateRoute = WorkoutsCreateImport.update({
  path: '/create',
  getParentRoute: () => WorkoutsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-exercise': {
      id: '/create-exercise'
      path: '/create-exercise'
      fullPath: '/create-exercise'
      preLoaderRoute: typeof CreateExerciseImport
      parentRoute: typeof rootRoute
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsImport
      parentRoute: typeof rootRoute
    }
    '/workouts/create': {
      id: '/workouts/create'
      path: '/create'
      fullPath: '/workouts/create'
      preLoaderRoute: typeof WorkoutsCreateImport
      parentRoute: typeof WorkoutsImport
    }
  }
}

// Create and export the route tree

interface WorkoutsRouteChildren {
  WorkoutsCreateRoute: typeof WorkoutsCreateRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsCreateRoute: WorkoutsCreateRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-exercise': typeof CreateExerciseRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/workouts/create': typeof WorkoutsCreateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-exercise': typeof CreateExerciseRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/workouts/create': typeof WorkoutsCreateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-exercise': typeof CreateExerciseRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/workouts/create': typeof WorkoutsCreateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-exercise'
    | '/exercises'
    | '/login'
    | '/signup'
    | '/workouts'
    | '/workouts/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-exercise'
    | '/exercises'
    | '/login'
    | '/signup'
    | '/workouts'
    | '/workouts/create'
  id:
    | '__root__'
    | '/'
    | '/create-exercise'
    | '/exercises'
    | '/login'
    | '/signup'
    | '/workouts'
    | '/workouts/create'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateExerciseRoute: typeof CreateExerciseRoute
  ExercisesRoute: typeof ExercisesRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateExerciseRoute: CreateExerciseRoute,
  ExercisesRoute: ExercisesRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WorkoutsRoute: WorkoutsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-exercise",
        "/exercises",
        "/login",
        "/signup",
        "/workouts"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-exercise": {
      "filePath": "create-exercise.tsx"
    },
    "/exercises": {
      "filePath": "exercises.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/workouts": {
      "filePath": "workouts.tsx",
      "children": [
        "/workouts/create"
      ]
    },
    "/workouts/create": {
      "filePath": "workouts.create.tsx",
      "parent": "/workouts"
    }
  }
}
ROUTE_MANIFEST_END */
