/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkoutsImport } from './routes/workouts'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as ExercisesIndexImport } from './routes/exercises/index'
import { Route as WorkoutsCreateImport } from './routes/workouts.create'
import { Route as ExercisesCreateExerciseImport } from './routes/exercises/create-exercise'
import { Route as ExercisesExerciseIdImport } from './routes/exercises/$exerciseId'

// Create/Update Routes

const WorkoutsRoute = WorkoutsImport.update({
  path: '/workouts',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExercisesIndexRoute = ExercisesIndexImport.update({
  path: '/exercises/',
  getParentRoute: () => rootRoute,
} as any)

const WorkoutsCreateRoute = WorkoutsCreateImport.update({
  path: '/create',
  getParentRoute: () => WorkoutsRoute,
} as any)

const ExercisesCreateExerciseRoute = ExercisesCreateExerciseImport.update({
  path: '/exercises/create-exercise',
  getParentRoute: () => rootRoute,
} as any)

const ExercisesExerciseIdRoute = ExercisesExerciseIdImport.update({
  path: '/exercises/$exerciseId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsImport
      parentRoute: typeof rootRoute
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdImport
      parentRoute: typeof rootRoute
    }
    '/exercises/create-exercise': {
      id: '/exercises/create-exercise'
      path: '/exercises/create-exercise'
      fullPath: '/exercises/create-exercise'
      preLoaderRoute: typeof ExercisesCreateExerciseImport
      parentRoute: typeof rootRoute
    }
    '/workouts/create': {
      id: '/workouts/create'
      path: '/create'
      fullPath: '/workouts/create'
      preLoaderRoute: typeof WorkoutsCreateImport
      parentRoute: typeof WorkoutsImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface WorkoutsRouteChildren {
  WorkoutsCreateRoute: typeof WorkoutsCreateRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsCreateRoute: WorkoutsCreateRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/create-exercise': typeof ExercisesCreateExerciseRoute
  '/workouts/create': typeof WorkoutsCreateRoute
  '/exercises': typeof ExercisesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/create-exercise': typeof ExercisesCreateExerciseRoute
  '/workouts/create': typeof WorkoutsCreateRoute
  '/exercises': typeof ExercisesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/create-exercise': typeof ExercisesCreateExerciseRoute
  '/workouts/create': typeof WorkoutsCreateRoute
  '/exercises/': typeof ExercisesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/workouts'
    | '/exercises/$exerciseId'
    | '/exercises/create-exercise'
    | '/workouts/create'
    | '/exercises'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/workouts'
    | '/exercises/$exerciseId'
    | '/exercises/create-exercise'
    | '/workouts/create'
    | '/exercises'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/workouts'
    | '/exercises/$exerciseId'
    | '/exercises/create-exercise'
    | '/workouts/create'
    | '/exercises/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  ExercisesCreateExerciseRoute: typeof ExercisesCreateExerciseRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WorkoutsRoute: WorkoutsRouteWithChildren,
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  ExercisesCreateExerciseRoute: ExercisesCreateExerciseRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/signup",
        "/workouts",
        "/exercises/$exerciseId",
        "/exercises/create-exercise",
        "/exercises/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/workouts": {
      "filePath": "workouts.tsx",
      "children": [
        "/workouts/create"
      ]
    },
    "/exercises/$exerciseId": {
      "filePath": "exercises/$exerciseId.tsx"
    },
    "/exercises/create-exercise": {
      "filePath": "exercises/create-exercise.tsx"
    },
    "/workouts/create": {
      "filePath": "workouts.create.tsx",
      "parent": "/workouts"
    },
    "/exercises/": {
      "filePath": "exercises/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
